### ISSUE TITLE
Issue in export API

### ISSUE THREAD

**Issue by ssnirgudkar** [segments-ai/segments-ai#4] opened 2021-08-01 12:24 UTC
Hello Bert, 

Facing an issue while exporting dataset in coco-panoptic format through the export API.-  

"NameError: name 'regionprops' is not defined" 

Code-  
from segments import SegmentsDataset
from segments.utils import export_dataset
dataset = SegmentsDataset(release, labelset='ground-truth', filter_by=['labeled', 'reviewed'])

# Export to COCO panoptic format
export_dataset(dataset, export_format='coco-panoptic')

---------------

It works for other formats like semantic , semantic-color. Did you just enhance the export API to support these? it will help me so I don't need to now convert the instance ids to category ids at my end. Are they expected to also return a json, as I only see images in the output of export. 

Best,
Shailesh

**Comment by dbbert** [comment] 2021-08-02 17:14
Thanks for letting us know Shailesh! I've pushed a fix.

This was caused by the previous update where we added those additional export formats - which indeed don't return a json, by the way.

**Closed by dbbert** 2021-08-02 17:14 UTC
